# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Nikola Djordjević 
tagline: Student
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Accustomed to team work but independent when it comes to individual assignments. 
Creative,communicative,professional,dedicated,hard worker. Fast problem solver. I understand 
responsibility and i give my best in everything I do. Eager to learn and improve myself,enthusiastic about my work.
Worked in Cybele Technologies IT company for one year. Currently absolvent year of the university. '

#sidebar links
email: nikola.djordjevic1412@gmail.com
phone: 069 140 2220
github: NikolaDjordjevic1412
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
